### ISSUE TITLE
add wiktionary  to sources

### ISSUE THREAD

**Issue by client9** [client9/misspell-source-data#5]
cc: @scop

wiktionary appears to have a 1.7M word list that is semi-downloadable.

https://archive.org/details/enwiktionary-20160801

One of the main problems with `misspell` is that the commonly used word lists are very incomplete and the update process is really slow.  Betters lists == less false positives.

**Comment by client9** [comment]
hmmm. Unfortunately, the  easy word list is a list of words *from all languages* with definitions in English.  Even filtering out non-ascii words resulting in 2M words.

**Comment by scop** [comment]
Interesting. Which file specifically do you mean?

**Comment by client9** [comment]
In https://archive.org/details/enwiktionary-20160801

This file
https://archive.org/download/enwiktionary-20160801/enwiktionary-20160801-all-titles.gz

is "all words" for "all languages".

This file
https://archive.org/download/enwiktionary-20160820/enwiktionary-20160820-category.sql.gz

is better but it's 2gigabyte mysql dump file.  It a lot of effort to make it useful, but added about 400,000 new "valid" English words to my list.  From this,  about 1400 false positives were eliminated:

https://github.com/client9/misspell/issues/84

But even with all this you found "subscripting" :-)

Enjoy and thank you!

n

**Comment by scop** [comment]
Cool. By the way, it's spelled Wiktionary, not Wikitionary (errors in sources/words-wikitionary dir name, as well as sources/words-wikitionary/* files...) :)

**Comment by client9** [comment]
HAHAHAHAHAHAHA 

Do you see why I wrote this tool?   I can't spell anything.
