### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by scop** [client9/misspell-source-data#6]
- [x] patchers->patches
- [ ] subscripting->subscription
- [x] profilers->profiles
- [x] archivers->archives
- [x] picklers->pickles

**Comment by client9** [comment]
Thanks! 

'll look, in the future, just add then to 'misspell'

Also I just fixed up 1400 false positives:
https://github.com/client9/misspell/issues/84

**Comment by client9** [comment]
"subscripting" -- thats a good one!  will fix shortly.

thanks again for these reports!

n
